---
- name: Homework playbook for Netology ML
  hosts: all
  become: yes  # Используем привилегии sudo
  vars:
    packages:
      - net-tools
      - git
      - tree
      - htop
      - mc
      - vim
    users:
      - devops_1
      - test_1

  tasks:
    - name: Ensure hosts are reachable
      ping:

    - name: Update package repository cache and install packages
      apt:
        update_cache: yes
        name: "{{ packages }}"
        state: present

    - name: Create ansible user
      user:
        name: ansible
        state: present
        create_home: yes

    - name: Ensure /home/ansible directory exists
      file:
        path: /home/ansible
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Copy test.txt file to remote hosts
      copy:
        src: /ansible/test.txt
        dest: /home/ansible/test.txt
        owner: ansible
        group: ansible

    - name: Create users and their home directories
      loop: "{{ users }}"
      user:
        name: "{{ item }}"
        state: present
        create_home: yes
